import { ThemeConfig } from '../types/catalog';

export const PREBUILT_THEMES: ThemeConfig[] = [
  {
    themeId: 'modern-minimal',
    themeName: 'Modern Minimal',
    primaryColor: '#0f172a',
    secondaryColor: '#f1f5f9',
    backgroundColor: '#ffffff',
    textColor: '#1e293b',
    buttonColor: '#0f172a',
    fontFamily: 'Plus Jakarta Sans',
    cardStyle: 'border',
    headerStyle: 'minimal',
  },
  {
    themeId: 'elegant',
    themeName: 'Elegant Rose',
    primaryColor: '#9f1239',
    secondaryColor: '#ffe4e6',
    backgroundColor: '#fff1f2',
    textColor: '#881337',
    buttonColor: '#be123c',
    fontFamily: 'Playfair Display',
    cardStyle: 'shadow',
    headerStyle: 'centered',
  },
  {
    themeId: 'cafe',
    themeName: 'Cafe & Warm',
    primaryColor: '#78350f',
    secondaryColor: '#fef3c7',
    backgroundColor: '#fffbe6',
    textColor: '#1c1917',
    buttonColor: '#92400e',
    fontFamily: 'Plus Jakarta Sans',
    cardStyle: 'shadow',
    headerStyle: 'hero',
  },
  {
    themeId: 'restaurant',
    themeName: 'Restaurant Gold',
    primaryColor: '#b45309',
    secondaryColor: '#fef3c7',
    backgroundColor: '#fafaf9',
    textColor: '#292524',
    buttonColor: '#d97706',
    fontFamily: 'Playfair Display',
    cardStyle: 'glass',
    headerStyle: 'hero',
  },
  {
    themeId: 'fashion',
    themeName: 'Fashion Vogue',
    primaryColor: '#18181b',
    secondaryColor: '#f4f4f5',
    backgroundColor: '#ffffff',
    textColor: '#27272a',
    buttonColor: '#000000',
    fontFamily: 'Playfair Display',
    cardStyle: 'border',
    headerStyle: 'banner',
  },
  {
    themeId: 'product-store',
    themeName: 'Product Store Blue',
    primaryColor: '#0284c7',
    secondaryColor: '#e0f2fe',
    backgroundColor: '#f8fafc',
    textColor: '#0f172a',
    buttonColor: '#0284c7',
    fontFamily: 'Plus Jakarta Sans',
    cardStyle: 'rounded',
    headerStyle: 'hero',
  },
  {
    themeId: 'corporate',
    themeName: 'Corporate Emerald',
    primaryColor: '#065f46',
    secondaryColor: '#d1fae5',
    backgroundColor: '#f0fdf4',
    textColor: '#064e3b',
    buttonColor: '#047857',
    fontFamily: 'Plus Jakarta Sans',
    cardStyle: 'shadow',
    headerStyle: 'centered',
  },
  {
    themeId: 'dark-premium',
    themeName: 'Dark Premium Cyber',
    primaryColor: '#38bdf8',
    secondaryColor: '#1e293b',
    backgroundColor: '#0f172a',
    textColor: '#f8fafc',
    buttonColor: '#0284c7',
    fontFamily: 'Plus Jakarta Sans',
    cardStyle: 'glass',
    headerStyle: 'hero',
  },
  {
    themeId: 'colorful',
    themeName: 'Colorful Pop',
    primaryColor: '#7c3aed',
    secondaryColor: '#ede9fe',
    backgroundColor: '#faf5ff',
    textColor: '#4c1d95',
    buttonColor: '#8b5cf6',
    fontFamily: 'Plus Jakarta Sans',
    cardStyle: 'rounded',
    headerStyle: 'banner',
  },
  {
    themeId: 'luxury',
    themeName: 'Luxury Gold Black',
    primaryColor: '#d97706',
    secondaryColor: '#27272a',
    backgroundColor: '#18181b',
    textColor: '#f4f4f5',
    buttonColor: '#b45309',
    fontFamily: 'Playfair Display',
    cardStyle: 'glass',
    headerStyle: 'centered',
  }
];
